src/focus/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import api
from . import views

router = routers.DefaultRouter()
router.register(r'competition', api.CompetitionViewSet)
router.register(r'training', api.TrainingViewSet)
router.register(r'competitor', api.CompetitorViewSet)
router.register(r'trainingpresence', api.TrainingpresenceViewSet)
router.register(r'driver', api.DriverViewSet)
router.register(r'event', api.EventViewSet)
router.register(r'result', api.ResultViewSet)
router.register(r'location', api.LocationViewSet)


urlpatterns = (
    # urls for Django Rest Framework API
    url(r'^api/v1/', include(router.urls)),
)

urlpatterns += (
    # urls for Competition
    url(r'^focus/competition/$', views.CompetitionListView.as_view(), name='focus_competition_list'),
    url(r'^focus/competition/create/$', views.CompetitionCreateView.as_view(), name='focus_competition_create'),
    url(r'^focus/competition/detail/(?P<slug>\S+)/$', views.CompetitionDetailView.as_view(), name='focus_competition_detail'),
    url(r'^focus/competition/update/(?P<slug>\S+)/$', views.CompetitionUpdateView.as_view(), name='focus_competition_update'),
)

urlpatterns += (
    # urls for Training
    url(r'^focus/training/$', views.TrainingListView.as_view(), name='focus_training_list'),
    url(r'^focus/training/create/$', views.TrainingCreateView.as_view(), name='focus_training_create'),
    url(r'^focus/training/detail/(?P<slug>\S+)/$', views.TrainingDetailView.as_view(), name='focus_training_detail'),
    url(r'^focus/training/update/(?P<slug>\S+)/$', views.TrainingUpdateView.as_view(), name='focus_training_update'),
)

urlpatterns += (
    # urls for Competitor
    url(r'^focus/competitor/$', views.CompetitorListView.as_view(), name='focus_competitor_list'),
    url(r'^focus/competitor/create/$', views.CompetitorCreateView.as_view(), name='focus_competitor_create'),
    url(r'^focus/competitor/detail/(?P<slug>\S+)/$', views.CompetitorDetailView.as_view(), name='focus_competitor_detail'),
    url(r'^focus/competitor/update/(?P<slug>\S+)/$', views.CompetitorUpdateView.as_view(), name='focus_competitor_update'),
)

urlpatterns += (
    # urls for Trainingpresence
    url(r'^focus/trainingpresence/$', views.TrainingpresenceListView.as_view(), name='focus_trainingpresence_list'),
    url(r'^focus/trainingpresence/create/$', views.TrainingpresenceCreateView.as_view(), name='focus_trainingpresence_create'),
    url(r'^focus/trainingpresence/detail/(?P<slug>\S+)/$', views.TrainingpresenceDetailView.as_view(), name='focus_trainingpresence_detail'),
    url(r'^focus/trainingpresence/update/(?P<slug>\S+)/$', views.TrainingpresenceUpdateView.as_view(), name='focus_trainingpresence_update'),
)

urlpatterns += (
    # urls for Driver
    url(r'^focus/driver/$', views.DriverListView.as_view(), name='focus_driver_list'),
    url(r'^focus/driver/create/$', views.DriverCreateView.as_view(), name='focus_driver_create'),
    url(r'^focus/driver/detail/(?P<slug>\S+)/$', views.DriverDetailView.as_view(), name='focus_driver_detail'),
    url(r'^focus/driver/update/(?P<slug>\S+)/$', views.DriverUpdateView.as_view(), name='focus_driver_update'),
)

urlpatterns += (
    # urls for Event
    url(r'^focus/event/$', views.EventListView.as_view(), name='focus_event_list'),
    url(r'^focus/event/create/$', views.EventCreateView.as_view(), name='focus_event_create'),
    url(r'^focus/event/detail/(?P<slug>\S+)/$', views.EventDetailView.as_view(), name='focus_event_detail'),
    url(r'^focus/event/update/(?P<slug>\S+)/$', views.EventUpdateView.as_view(), name='focus_event_update'),
)

urlpatterns += (
    # urls for Result
    url(r'^focus/result/$', views.ResultListView.as_view(), name='focus_result_list'),
    url(r'^focus/result/create/$', views.ResultCreateView.as_view(), name='focus_result_create'),
    url(r'^focus/result/detail/(?P<slug>\S+)/$', views.ResultDetailView.as_view(), name='focus_result_detail'),
    url(r'^focus/result/update/(?P<slug>\S+)/$', views.ResultUpdateView.as_view(), name='focus_result_update'),
)

urlpatterns += (
    # urls for Location
    url(r'^focus/location/$', views.LocationListView.as_view(), name='focus_location_list'),
    url(r'^focus/location/create/$', views.LocationCreateView.as_view(), name='focus_location_create'),
    url(r'^focus/location/detail/(?P<slug>\S+)/$', views.LocationDetailView.as_view(), name='focus_location_detail'),
    url(r'^focus/location/update/(?P<slug>\S+)/$', views.LocationUpdateView.as_view(), name='focus_location_update'),
)

src/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

src/project_name/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/profiles/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
import uuid
from django.db import models
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField

USER_TYPES = (
    ('Neu','Neu'),
    ('Athlet','Athlet'),
    ('Eltern','Eltern'),
    ('Coach', 'Coach'),
)


class BaseProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                primary_key=True)
    slug = models.UUIDField(default=uuid.uuid4, blank=True, editable=False)
    # Add more user profile fields here. Make sure they are nullable
    # or with default values
    picture = models.ImageField('Profilbild',
                                upload_to='profile_pics/%Y-%m-%d/',
                                null=True,
                                blank=True)
    bio = models.CharField("Über mich", max_length=200, blank=True, null=True)
    email_verified = models.BooleanField("Email verified", default=False)
    user_type = models.CharField(max_length=20, choices=USER_TYPES, default='Neu')
    active = models.BooleanField(default=True)
    bdate = models.DateField("Geburtsdatum",auto_now=False, auto_now_add=False, blank=True, null=True, default='2099-01-20')
    phone_number = PhoneNumberField("Natelnummer",blank=True, null=True, default='+41791234678')
    street = models.CharField(max_length=255, blank=True, null=True, default='Marktgasse 1')
    city = models.CharField(max_length=255, blank=True, null=True, default='8400 Winterthur')

    class Meta:
        abstract = True

    @property
    def is_coach(self):
        if self.user_type == 'Coach':
            return True
        else:
            return False


@python_2_unicode_compatible
class Profile(BaseProfile):
    def __str__(self):
        return "{}'s profile". format(self.user)

src/profiles/forms.py
from __future__ import unicode_literals
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from django.contrib.auth import get_user_model
from django.forms.widgets import DateInput
from . import models

User = get_user_model()


class UserForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('name'),
            )

    class Meta:
        model = User
        fields = ['name']


class ProfileForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('picture'),
            Field('bio'),
            Field('phone_number'),
            Field('bdate'),
            Field('street'),
            Field('city'),
            Submit('update', 'Update', css_class="btn-success"),
            )


    class Meta:
        model = models.Profile
        fields = ['picture', 'bio', 'bdate','phone_number','street','city']

src/profiles/views.py
from __future__ import unicode_literals
from django.views import generic
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from . import forms
from . import models
import datetime


class ShowProfile(LoginRequiredMixin, generic.TemplateView):
    template_name = "profiles/show_profile.html"
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        slug = self.kwargs.get('slug')
        if slug:
            profile = get_object_or_404(models.Profile, slug=slug)
            user = profile.user
        else:
            user = self.request.user

        if user == self.request.user:
            kwargs["editable"] = True
        kwargs["show_user"] = user
        return super(ShowProfile, self).get(request, *args, **kwargs)


class EditProfile(LoginRequiredMixin, generic.TemplateView):
    template_name = "profiles/edit_profile.html"
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):
        user = self.request.user
        if "user_form" not in kwargs:
            kwargs["user_form"] = forms.UserForm(instance=user)
        if "profile_form" not in kwargs:
            kwargs["profile_form"] = forms.ProfileForm(instance=user.profile)
        return super(EditProfile, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        user = self.request.user
        user_form = forms.UserForm(request.POST, instance=user)
        profile_form = forms.ProfileForm(request.POST,
                                         request.FILES,
                                         instance=user.profile)
        if not (user_form.is_valid() and profile_form.is_valid()):
            message = ""
            if profile_form.errors:
                if 'phone_number' in profile_form.errors.keys():
                    message += "Bitte gibt Deine Natelnummer wie folgt ein: +41791234567. "
                if 'bdate' in profile_form.errors.keys():
                    message += "Bitte gibt das Geburtsdatum wie folgt ein: 2002-01-15 für 15. Januar 2002"
            messages.error(request, message)
            user_form = forms.UserForm(instance=user)
            profile_form = forms.ProfileForm(instance=user.profile)
            return super(EditProfile, self).get(request,
                                                user_form=user_form,
                                                profile_form=profile_form)
        # Both forms are fine. Time to save!
        user_form.save()
        profile = profile_form.save(commit=False)
        profile.user = user
        profile.save()
        messages.success(request, "Profile details saved!")
        return redirect("profiles:show_self")

src/profiles/templates/profiles/edit_profile.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}{{ block.super }}Profile{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div class="container">
  <h1 class="text-primary">Profil abändern</h1>
  <hr>
  <div class="row">
    <!-- left column -->
    <div class="col-md-3">
      <div class="text-center">
        <img title="profile picture" class="img-circle img-responsive" src="{% thumbnail user.profile.picture|default:'default_profile.png' 140x140 crop %}">
      </div>
    </div>
      
    <!-- edit form column -->
    <div class="col-md-9">
      <h3>Persönliche Informationen</h3>
      <form enctype="multipart/form-data" method="post">
	{% crispy user_form %}
	{% crispy profile_form %}
      </form>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <a class="btn btn-default pull-right" href="{% url 'accounts:password-change' %}">Passwort ändern</a>
    </div>
  </div>
</div>
{% endblock %}

 <script>
  $(function() {
    $( ".datepicker" ).datepicker({
      // You can put more options here.

    });
  });
  </script>

src/profiles/templates/profiles/show_profile.html
{% extends "base.html" %}

{% load staticfiles %}
{% load thumbnail %}

{% block title %}{{ block.super }}Profile{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" %}
{% endblock %}

{% block container %}

<div class="container profile-head">
  <div class="row">
    <div class="col-sm-10 text-center">
      <h1 style="color:white">{{ show_user.get_full_name }}</h1>
    </div>
    <div class="col-sm-2"><img title="profile picture" class="img-circle img-responsive" src="{% thumbnail show_user.profile.picture|default:'default_profile.png' 140x140 crop %}">
    </div>
  </div>
</div>

<div class="container profile-body">
  <div class="row">
    <div class="col-sm-4">
      <ul class="list-group">
        <li class="list-group-item text-muted">Profile</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Email:</strong></span> {{ show_user.email|default:"missing" }}
	  {% if show_user.profile.email_verified %}
	    <span class="glyphicon glyphicon-ok-circle" aria-hidden="true" title="This email address has been verified"></span>
	    <span class="sr-only">Verified</span>
	  {% else %}
	    <span class="glyphicon glyphicon-warning-sign" aria-hidden="true" title="This email address is not verified"></span>
	    <span class="sr-only">Not Verified</span>
	  {% endif %}
	</li>
          <li class="list-group-item text-right"><span class="pull-left"><strong>Joined</strong></span> {{ show_user.date_joined }}</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Last seen</strong></span> {{ show_user.last_login }}</li>
      </ul>
    </div>
    <div class="col-sm-8">
      <div class="panel panel-default">
        <div class="panel-heading">{{ show_user.get_full_name }}'s Profil
	  {% if show_user.profile.slug %}
	    <a href="{% url 'profiles:show' show_user.profile.slug %}">
	    	<span class="glyphicon glyphicon-link" aria-hidden="true" title="Profile permalink"></span>
	    	<span class="sr-only">Permalink</span></a> {{ show_user.profile.get_absolute_url }}
	  {% else %}
		<a href="https://github.com/arocks/edge/issues/40" target="_blank"><span>No permalink. See this issue.</span></a>
	  {% endif %}
	</div>
        <div class="panel-body">
	  <p><strong>Über mich</strong>: {{ show_user.profile.bio }}</p>
            <p><strong>Strasse</strong>: {{ show_user.profile.street }}</p>
            <p><strong>Ort</strong>: {{ show_user.profile.city }}</p>
            <p><strong>Natelnummer</strong>: {{ show_user.profile.phone_number }}</p>
            <p><strong>Geburtsdatum</strong>: {{show_user.profile.bdate}}</p>
            <p><strong>Rolle</strong>: {{ show_user.profile.user_type }}</p>

	</div>
      </div>
    </div>
  </div>
              {% if editable %}
    <p>Bitte vervollständige Dein Profil hier:</p>
      <a href="{% url 'profiles:edit_self' %}" class="btn btn-info">Profil abändern</a>
      {% endif %}
</div>

{% endblock %}