src/focus/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import api
from . import views

router = routers.DefaultRouter()
router.register(r'competition', api.CompetitionViewSet)
router.register(r'training', api.TrainingViewSet)
router.register(r'competitor', api.CompetitorViewSet)
router.register(r'trainingpresence', api.TrainingpresenceViewSet)
router.register(r'driver', api.DriverViewSet)
router.register(r'event', api.EventViewSet)
router.register(r'result', api.ResultViewSet)
router.register(r'location', api.LocationViewSet)


urlpatterns = (
    # urls for Django Rest Framework API
    url(r'^api/v1/', include(router.urls)),
)

urlpatterns += (
    # urls for Competition
    url(r'^focus/competition/$', views.CompetitionListView.as_view(), name='focus_competition_list'),
    url(r'^focus/competition/create/$', views.CompetitionCreateView.as_view(), name='focus_competition_create'),
    url(r'^focus/competition/detail/(?P<slug>\S+)/$', views.CompetitionDetailView.as_view(), name='focus_competition_detail'),
    url(r'^focus/competition/update/(?P<slug>\S+)/$', views.CompetitionUpdateView.as_view(), name='focus_competition_update'),
)

urlpatterns += (
    # urls for Training
    url(r'^focus/training/$', views.TrainingListView.as_view(), name='focus_training_list'),
    url(r'^focus/training/create/$', views.TrainingCreateView.as_view(), name='focus_training_create'),
    url(r'^focus/training/detail/(?P<slug>\S+)/$', views.TrainingDetailView.as_view(), name='focus_training_detail'),
    url(r'^focus/training/update/(?P<slug>\S+)/$', views.TrainingUpdateView.as_view(), name='focus_training_update'),
)

urlpatterns += (
    # urls for Competitor
    url(r'^focus/competitor/$', views.CompetitorListView.as_view(), name='focus_competitor_list'),
    url(r'^focus/competitor/create/$', views.CompetitorCreateView.as_view(), name='focus_competitor_create'),
    url(r'^focus/competitor/detail/(?P<slug>\S+)/$', views.CompetitorDetailView.as_view(), name='focus_competitor_detail'),
    url(r'^focus/competitor/update/(?P<slug>\S+)/$', views.CompetitorUpdateView.as_view(), name='focus_competitor_update'),
)

urlpatterns += (
    # urls for Trainingpresence
    url(r'^focus/trainingpresence/$', views.TrainingpresenceListView.as_view(), name='focus_trainingpresence_list'),
    url(r'^focus/trainingpresence/create/$', views.TrainingpresenceCreateView.as_view(), name='focus_trainingpresence_create'),
    url(r'^focus/trainingpresence/detail/(?P<slug>\S+)/$', views.TrainingpresenceDetailView.as_view(), name='focus_trainingpresence_detail'),
    url(r'^focus/trainingpresence/update/(?P<slug>\S+)/$', views.TrainingpresenceUpdateView.as_view(), name='focus_trainingpresence_update'),
)

urlpatterns += (
    # urls for Driver
    url(r'^focus/driver/$', views.DriverListView.as_view(), name='focus_driver_list'),
    url(r'^focus/driver/create/$', views.DriverCreateView.as_view(), name='focus_driver_create'),
    url(r'^focus/driver/detail/(?P<slug>\S+)/$', views.DriverDetailView.as_view(), name='focus_driver_detail'),
    url(r'^focus/driver/update/(?P<slug>\S+)/$', views.DriverUpdateView.as_view(), name='focus_driver_update'),
)

urlpatterns += (
    # urls for Event
    url(r'^focus/event/$', views.EventListView.as_view(), name='focus_event_list'),
    url(r'^focus/event/create/$', views.EventCreateView.as_view(), name='focus_event_create'),
    url(r'^focus/event/detail/(?P<slug>\S+)/$', views.EventDetailView.as_view(), name='focus_event_detail'),
    url(r'^focus/event/update/(?P<slug>\S+)/$', views.EventUpdateView.as_view(), name='focus_event_update'),
)

urlpatterns += (
    # urls for Result
    url(r'^focus/result/$', views.ResultListView.as_view(), name='focus_result_list'),
    url(r'^focus/result/create/$', views.ResultCreateView.as_view(), name='focus_result_create'),
    url(r'^focus/result/detail/(?P<slug>\S+)/$', views.ResultDetailView.as_view(), name='focus_result_detail'),
    url(r'^focus/result/update/(?P<slug>\S+)/$', views.ResultUpdateView.as_view(), name='focus_result_update'),
)

urlpatterns += (
    # urls for Location
    url(r'^focus/location/$', views.LocationListView.as_view(), name='focus_location_list'),
    url(r'^focus/location/create/$', views.LocationCreateView.as_view(), name='focus_location_create'),
    url(r'^focus/location/detail/(?P<slug>\S+)/$', views.LocationDetailView.as_view(), name='focus_location_detail'),
    url(r'^focus/location/update/(?P<slug>\S+)/$', views.LocationUpdateView.as_view(), name='focus_location_update'),
)

src/lvwyoungtalents/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import focus.urls
from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^', include(focus.urls, namespace='focus')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/templates/_brandname.html
LVW Young Talents

src/templates/_navbar.html
<li {% if active_link == "home" %}class="active"{% endif %}><a href="{% url 'home' %}">Home</a></li>
<li {% if active_link == "training" %}class="active"{% endif %}><a href="{% url 'focus:focus_training_list' %}">Trainings</a></li>
<li {% if active_link == "competition" %}class="active"{% endif %}><a href="{% url 'focus:focus_competition_list' %}">Wettkämpfe & Events</a></li>
<li {% if active_link == "about" %}class="active"{% endif %}><a href="{% url 'about' %}">Über uns</a></li>

src/templates/about.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1 style="color:#ffffff">{% include "_brandname.html" %}</h1>
        <h4 style="color:#ffffff">Engagement, Kameradschaft, Bodenständigkeit.</h4>
      </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Coaching Team</h2>
        <p class="lead">Die Trainer der MU16</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="/static/site/img/tg.jpg" alt="profile pic"></div>
        <p class="heavy text-center">Daniel Brunner</p>
        <h2>Mehrkampf</h2>
        <p>Daniel hat sich nach seiner erfolgreichen Karriere als Zehnkämpfer und dem Sprung ins Nationalteam nach einer Verletzung (zu) früh entscheiden müssen den Mehrkampf aufzugeben. Danach fokussierte er sich auf seine Paradedisziplin den Stabhochsprung und das Coaching. Beruflich ist er Doktorant an der ZHAW hier in Winterthur und reist dafür immer wieder in den Norden nach Norwegen. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="/static/site/img/pb.jpg" alt="profile pic"></div>
        <p class="heavy text-center">Dr. Pascal Buri</p>
        <h2>Mittelstrecken</h2>
        <p>Dr. Pascal Buri hat über mehrere Jahre Mehrkampf trainiert und zusammen mit Daniel und Roger etliche Zehnkampf-Wochenenden verbracht. Nach einigen Saisons über die 400m Hürden ist er nun bei den Mittelstrecklern gelandet und läuft vor allem für's Leben gern. Beruflich beschäftigt sich Pascal mit Gletschern. Das trifft sich gut, da er sich sehr gern in den Bergen aufhält. Seine Lieblingstrainings sind Bahntrainings jeglicher Geschwindigkeit und seine Lieblingsdisziplin ist Kugelstossen. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="/static/site/img/rr.jpg" alt="profile pic"></div>
        <p class="heavy text-center">Roger Rüegg</p>
        <h2>Mehrkampf</h2>
        <p>Roger hat sich in seiner Aktivzeit ganz dem Zehnkampf verschrieben. Obwohl sein Doktor ihm mit 18 Jahren empfohlen hat nur noch Golf zu spielen, hat er es doch noch bis zu Länderkämpfen und dem Kantonalturnfestsieg 11 Jahre später geschafft seine Leidenschaft auszuüben. Beruflich ist Roger Portfoliomanager und Doktorant an der Universität Zürich, wo er nicht mehr seine Weite, Höhe oder Zeit optimiert sondern die Rendite und das Risiko des Portfolios.</p>
      </div>
    </div>
    </div>
  </div>
</div>
<!--
<div id="sec3">
  <div class="container">
    <div class="row">
      <div id="map-outer" class="col-md-12">
        <div id="address" class="col-md-4">
          <h2>Our Location</h2>
          <address>
            <strong>Edge Solutions Ltd.</strong><br>
            Taj Mahal<br>
            Agra<br>
            Uttar Pradesh<br>
            India - 282001<br>
            <abbr>P:</abbr> +91 0562 222 6431
          </address>
        </div>
        <div id="map-container" class="col-md-8"></div>
      </div>
    </div>
  </div>
</div>
{% endblock container %}

{% block scripts %}
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script>

   function init_map() {
     // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(27.176141, 78.042370);

     var mapOptions = {
          center: myLocation,
          zoom: 14
     };

	 var marker = new google.maps.Marker({
	   position: myLocation,
	   title:"We are here"});

     var map = new google.maps.Map(document.getElementById("map-container"),
                                   mapOptions);
	 marker.setMap(map);
   }

   google.maps.event.addDomListener(window, 'load', init_map);
  </script>
--!>
{% endblock scripts %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}
    
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Arun Ravindran">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/moment.min.js' %}"></script>

    <link href="{% static 'bootstrap/css/bootstrap-datetimepicker.css' %}" type="text/css" media="all" rel="stylesheet" />
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap-datetimepicker.js' %}"></script>
    <!-- {{ form.media }}-->

  <script>
  $(document).ready(function() {
    $("#datepicker").datepicker();
  });
  </script>

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

  </head>

  <body>

    {% block navbar %}
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
              <img src="{% static 'site/img/logo.png' %}" alt="logo">
              {% include "_brandname.html" %}
            {% endblock %}
          </a>
        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar-left %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% block navbar-right %}
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
			<img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
			{{ user.get_full_name|truncatechars:20 }}
			<span class="caret"></span>
		    </a>
		    
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                  </ul>
                </li>
              {% endif %}
            {% endblock %}
          </ul>
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
    </div>
    {% endblock navbar %}

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}
    
    {% block container %}
    <div class="container">

      <div class="starter-template">
        <h1>New Project</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
    {% endblock container %}

    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <a name="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-6">
              <p>&copy; LV Winterthur {% now 'Y' %}</p>
          </div>
          <!--<div class="col-lg-6 text-right">
            Connect with us on
            <a href="#"><i class="fa fa-facebook"></i> Facebook</a> or
            <a href="#"><i class="fa fa-twitter"></i> Twitter</a>
          </div>-->
        </div>
            </div>
      </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

src/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

{% block splash %}
  <div class="jumbotron jumbotron-carousel corporate-jumbo">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-8">
          <h1 style="color:whitesmoke; border: None; border-color: transparent;">{% include "_brandname.html" %}</h1>
          <p style="color:whitesmoke; border: None; border-color: transparent;">Engagement, Kameradschaft, Bodenständigkeit.</p>
	  <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Ich möchte dabei sein!</a>
        </div>
        <div class="col-md-4 col-sm-4">

        </div>
      </div>
    </div>
  </div>
{% endblock splash %}

{% block container %}
<!-- Benefits of the Django application -->
<a name="about"></a>

<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <h2>Training</h2>
      <p>Wir bereiten die U16 der LV Winterthur auf eine erfolgreiche Karriere als Leistungsportler vor. Bei Möglichkeit
    kann mit den Aktiven der LV Winterthur ein zusätzliches Fördertraining bestritten werden.
    Die nächsten Trainings finden wie folgt statt ...</p>
      <p><a class="btn btn-primary" href="{% url 'focus:focus_training_list' %}" role="button">Mehr dazu &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>Wettkämpfe</h2>
      <p>Wir möchten zu den besten in der Schweiz gehören, als Team und als Einzelathleten. Die wichtigsten Wettkämpfe bilden die Schweizer- und Kantonalmeisterschaften.
      Mit dem Trainingslager und Vorbereitungswettkämpfen sowie Teamevents bereiten wir uns optimal auf die Saisonhöhepunkte vor...</p>
      <p><a class="btn btn-primary" href="{% url 'focus:focus_competition_list' %}" role="button">Mehr dazu&raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>Philosophie</h2>
      <p>Engagement, Kameradschaft, Bodenständigkeit ist unser Motto. Wir trainieren konzentriert, motivieren uns gegenseitig
        und möchten grossen Spass an der Leichtathletik haben. </p>
      <p><a class="btn btn-primary" href="{% url 'about' %}" role="button">Mehr dazu &raquo;</a></p>
    </div>
  </div>
</div>

{% endblock container %}

{% block scripts %}
<script src="{% static 'site/js/site.js' %}"></script>
{% endblock scripts %}