src/focus/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import api
from . import views

router = routers.DefaultRouter()
router.register(r'competition', api.CompetitionViewSet)
router.register(r'training', api.TrainingViewSet)
router.register(r'competitor', api.CompetitorViewSet)
router.register(r'trainingpresence', api.TrainingpresenceViewSet)
router.register(r'driver', api.DriverViewSet)
router.register(r'event', api.EventViewSet)
router.register(r'result', api.ResultViewSet)
router.register(r'location', api.LocationViewSet)


urlpatterns = (
    # urls for Django Rest Framework API
    url(r'^api/v1/', include(router.urls)),
)

urlpatterns += (
    # urls for Competition
    url(r'^focus/competition/$', views.CompetitionListView.as_view(), name='focus_competition_list'),
    url(r'^focus/competition/create/$', views.CompetitionCreateView.as_view(), name='focus_competition_create'),
    url(r'^focus/competition/detail/(?P<slug>\S+)/$', views.CompetitionDetailView.as_view(), name='focus_competition_detail'),
    url(r'^focus/competition/update/(?P<slug>\S+)/$', views.CompetitionUpdateView.as_view(), name='focus_competition_update'),
)

urlpatterns += (
    # urls for Training
    url(r'^focus/training/$', views.TrainingListView.as_view(), name='focus_training_list'),
    url(r'^focus/training/create/$', views.TrainingCreateView.as_view(), name='focus_training_create'),
    url(r'^focus/training/detail/(?P<slug>\S+)/$', views.TrainingDetailView.as_view(), name='focus_training_detail'),
    url(r'^focus/training/update/(?P<slug>\S+)/$', views.TrainingUpdateView.as_view(), name='focus_training_update'),
)

urlpatterns += (
    # urls for Competitor
    url(r'^focus/competitor/$', views.CompetitorListView.as_view(), name='focus_competitor_list'),
    url(r'^focus/competitor/create/$', views.CompetitorCreateView.as_view(), name='focus_competitor_create'),
    url(r'^focus/competitor/detail/(?P<slug>\S+)/$', views.CompetitorDetailView.as_view(), name='focus_competitor_detail'),
    url(r'^focus/competitor/update/(?P<slug>\S+)/$', views.CompetitorUpdateView.as_view(), name='focus_competitor_update'),
)

urlpatterns += (
    # urls for Trainingpresence
    url(r'^focus/trainingpresence/$', views.TrainingpresenceListView.as_view(), name='focus_trainingpresence_list'),
    url(r'^focus/trainingpresence/create/$', views.TrainingpresenceCreateView.as_view(), name='focus_trainingpresence_create'),
    url(r'^focus/trainingpresence/detail/(?P<slug>\S+)/$', views.TrainingpresenceDetailView.as_view(), name='focus_trainingpresence_detail'),
    url(r'^focus/trainingpresence/update/(?P<slug>\S+)/$', views.TrainingpresenceUpdateView.as_view(), name='focus_trainingpresence_update'),
)

urlpatterns += (
    # urls for Driver
    url(r'^focus/driver/$', views.DriverListView.as_view(), name='focus_driver_list'),
    url(r'^focus/driver/create/$', views.DriverCreateView.as_view(), name='focus_driver_create'),
    url(r'^focus/driver/detail/(?P<slug>\S+)/$', views.DriverDetailView.as_view(), name='focus_driver_detail'),
    url(r'^focus/driver/update/(?P<slug>\S+)/$', views.DriverUpdateView.as_view(), name='focus_driver_update'),
)

urlpatterns += (
    # urls for Event
    url(r'^focus/event/$', views.EventListView.as_view(), name='focus_event_list'),
    url(r'^focus/event/create/$', views.EventCreateView.as_view(), name='focus_event_create'),
    url(r'^focus/event/detail/(?P<slug>\S+)/$', views.EventDetailView.as_view(), name='focus_event_detail'),
    url(r'^focus/event/update/(?P<slug>\S+)/$', views.EventUpdateView.as_view(), name='focus_event_update'),
)

urlpatterns += (
    # urls for Result
    url(r'^focus/result/$', views.ResultListView.as_view(), name='focus_result_list'),
    url(r'^focus/result/create/$', views.ResultCreateView.as_view(), name='focus_result_create'),
    url(r'^focus/result/detail/(?P<slug>\S+)/$', views.ResultDetailView.as_view(), name='focus_result_detail'),
    url(r'^focus/result/update/(?P<slug>\S+)/$', views.ResultUpdateView.as_view(), name='focus_result_update'),
)

urlpatterns += (
    # urls for Location
    url(r'^focus/location/$', views.LocationListView.as_view(), name='focus_location_list'),
    url(r'^focus/location/create/$', views.LocationCreateView.as_view(), name='focus_location_create'),
    url(r'^focus/location/detail/(?P<slug>\S+)/$', views.LocationDetailView.as_view(), name='focus_location_detail'),
    url(r'^focus/location/update/(?P<slug>\S+)/$', views.LocationUpdateView.as_view(), name='focus_location_update'),
)

src/lvwyoungtalents/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import focus.urls
from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^', include(focus.urls, namespace='focus')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/focus/forms.py
from django import forms
from .models import Competition, Training, Competitor, Trainingpresence, Driver, Event, Result, Location
from datetimewidget.widgets import DateTimeWidget

class CompetitionForm(forms.ModelForm):
    class Meta:
        model = Competition
        fields = ['name', 'starttime', 'endtime', 'description', 'link', 'sign_in_date', 'subscription', 'selfsubscription', 'meeting_time', 'file', 'car_seats_required', 'car_seats_available', 'location', 'meetingpoint']
        widgets = {
            # Use localization and bootstrap 3
            'starttime': DateTimeWidget(attrs={'id': "starttime"}, options={'format':'yyyy-mm-dd hh:ii'}),
            'endtime': DateTimeWidget(attrs={'id': "endtime"}, options={'format':'yyyy-mm-dd hh:ii'}),
            'sign_in_date': DateTimeWidget(attrs={'id': "starttime"}, options={'format': 'yyyy-mm-dd hh:ii'}),
            'meeting_time': DateTimeWidget(attrs={'id': "endtime"}, options={'format': 'yyyy-mm-dd hh:ii'}),
        }

class TrainingForm(forms.ModelForm):
    class Meta:
        model = Training
        fields = ['name', 'starttime', 'endtime', 'intensity', 'short_description', 'detailed_description', 'file', 'location']
        widgets = {
            # Use localization and bootstrap 3
            'starttime': DateTimeWidget(attrs={'id': "starttime"}, options={'format':'yyyy-mm-dd hh:ii'}),
            'endtime': DateTimeWidget(attrs={'id': "endtime"}, options={'format':'yyyy-mm-dd hh:ii'}),
        }


class CompetitorForm(forms.ModelForm):
    class Meta:
        model = Competitor
        fields = ['yesorno', 'note', 'user', 'competition']


class TrainingpresenceForm(forms.ModelForm):
    class Meta:
        model = Trainingpresence
        fields = ['yesorno', 'excused', 'feedback_to_coach', 'feedback_to_athlete', 'user', 'training']


class DriverForm(forms.ModelForm):
    class Meta:
        model = Driver
        fields = ['number_seats', 'note', 'user', 'competition']


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'short_description', 'file', 'is_duration', 'is_distance', 'is_repetitions', 'detailed_description']


class ResultForm(forms.ModelForm):
    class Meta:
        model = Result
        fields = ['duration', 'distance', 'repetitions', 'note', 'user', 'event', 'location']


class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = ['name', 'address', 'googlemapurl', 'description']

src/focus/views.py
from django.views.generic import DetailView, ListView, UpdateView, CreateView
from .models import Competition, Training, Competitor, Trainingpresence, Driver, Event, Result, Location
from .forms import CompetitionForm, TrainingForm, CompetitorForm, TrainingpresenceForm, DriverForm, EventForm, ResultForm, LocationForm
from django.contrib.auth import get_user_model
from django.shortcuts import redirect
User = get_user_model()
import datetime
from django.utils import timezone
from django.contrib import messages

class CompetitionListView(ListView):
    model = Competition

    def post(self, request, *args, **kwargs):
        if 'abmelden' in request.POST:
            competition = Competition.objects.get(id=int(request.POST['abmelden']))
            if timezone.now() > competition.sign_in_date:
                message = "Bitte melde Dich bei Deinem Trainer für den Wettkampf '" + competition.name + "' die Anmeldefrist ist abgelaufen."
                messages.error(request, message)
            else:
                message = "Du bist erfolgreich für den Wettkampf '" + competition.name + "' abgemeldet. Bitte beachte die Details unter 'Wie melde ich mich an?'."
                messages.success(request, message)
                competitor = Competitor.objects.filter(competition=int(request.POST['abmelden']), user=request.user)[0]
                competitor.yesorno = False
                competitor.save()
        if 'anmelden' in request.POST:
            competition = Competition.objects.get(id=int(request.POST['anmelden']))
            if timezone.now() > competition.sign_in_date:
                message = "Bitte melde Dich bei Deinem Trainer für den Wettkampf '" + competition.name + "' die Anmeldefrist ist abgelaufen."
                messages.error(request, message)
            else:
                message = "Du bist erfolgreich für den Wettkampf '" + competition.name + "' angemeldet. Bitte beachte die Details unter 'Wie melde ich mich an?'."
                messages.success(request, message)
                competitor = Competitor.objects.filter(competition=int(request.POST['anmelden']), user=request.user)[0]
                competitor.yesorno = True
                competitor.save()
        return redirect('focus:focus_competition_list')

    def get_queryset(self):
        today = datetime.datetime.today()
        return Competition.objects.filter(endtime__gte=today).order_by('starttime')


class CompetitionCreateView(CreateView):
    model = Competition
    form_class = CompetitionForm


class CompetitionDetailView(DetailView):
    model = Competition

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(CompetitionDetailView, self).get_context_data(**kwargs)
        context['competitors'] = Competitor.objects.filter(competition=kwargs['object'].pk)
        return context


class CompetitionUpdateView(UpdateView):
    model = Competition
    form_class = CompetitionForm


class TrainingListView(ListView):
    model = Training

    def post(self, request, *args, **kwargs):
        if 'abmelden' in request.POST:
            presence = Trainingpresence.objects.filter(training=int(request.POST['abmelden']), user=request.user)[0]
            presence.excused = True
            presence.yesorno = False
            presence.save()
        if 'anmelden' in request.POST:
            presence = Trainingpresence.objects.filter(training=int(request.POST['anmelden']), user=request.user)[0]
            presence.excused = False
            presence.yesorno = True
            presence.save()
        return redirect('focus:focus_training_list')


    def get_queryset(self):
        today = datetime.datetime.today()
        return Training.objects.filter(endtime__gte=today).order_by('starttime')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(TrainingListView, self).get_context_data(**kwargs)
        return context


class TrainingCreateView(CreateView):
    model = Training
    form_class = TrainingForm


class TrainingDetailView(DetailView):
    model = Training


    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(TrainingDetailView, self).get_context_data(**kwargs)
        context['athletes'] = Trainingpresence.objects.filter(training=kwargs['object'].pk)
        return context


class TrainingUpdateView(UpdateView):
    model = Training
    form_class = TrainingForm


class CompetitorListView(ListView):
    model = Competitor


class CompetitorCreateView(CreateView):
    model = Competitor
    form_class = CompetitorForm


class CompetitorDetailView(DetailView):
    model = Competitor


class CompetitorUpdateView(UpdateView):
    model = Competitor
    form_class = CompetitorForm


class TrainingpresenceListView(ListView):
    model = Trainingpresence


class TrainingpresenceCreateView(CreateView):
    model = Trainingpresence
    form_class = TrainingpresenceForm


class TrainingpresenceDetailView(DetailView):
    model = Trainingpresence


class TrainingpresenceUpdateView(UpdateView):
    model = Trainingpresence
    form_class = TrainingpresenceForm


class DriverListView(ListView):
    model = Driver


class DriverCreateView(CreateView):
    model = Driver
    form_class = DriverForm


class DriverDetailView(DetailView):
    model = Driver


class DriverUpdateView(UpdateView):
    model = Driver
    form_class = DriverForm


class EventListView(ListView):
    model = Event


class EventCreateView(CreateView):
    model = Event
    form_class = EventForm


class EventDetailView(DetailView):
    model = Event


class EventUpdateView(UpdateView):
    model = Event
    form_class = EventForm


class ResultListView(ListView):
    model = Result


class ResultCreateView(CreateView):
    model = Result
    form_class = ResultForm


class ResultDetailView(DetailView):
    model = Result


class ResultUpdateView(UpdateView):
    model = Result
    form_class = ResultForm


class LocationListView(ListView):
    model = Location


class LocationCreateView(CreateView):
    model = Location
    form_class = LocationForm


class LocationDetailView(DetailView):
    model = Location


class LocationUpdateView(UpdateView):
    model = Location
    form_class = LocationForm

src/focus/templates/focus/competition_list.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load customtags %}

{% block title %}{{ block.super }}Wettkämpfe{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="competition" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1 style="color:#ffffff">{% include "_brandname.html" %}</h1>
        <h4 style="color:#ffffff">Engagement, Kameradschaft, Bodenständigkeit.</h4>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid">
<iframe src="https://calendar.google.com/calendar/embed?src=g7trtnc4b6ecbg490ph5f7gf88%40group.calendar.google.com&ctz=Europe%2FZurich" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe><tr>
{% if user.profile.is_coach %}
<p><a class="btn btn-default" href="{% url 'focus:focus_competition_create' %}">Neuer Event</a></p>
{% endif %}

    <form id="abmelden" method="post">
       <h1 >Wettkämpfe & Events</h1>
<table class="table table-hover table-bordered table-striped table-condensed">

    {% if not user.is_authenticated %}
    <td>Was</td>
    <td>Von</td>
    <td>Bis</td>
    <td>Wo</td>
</tr>
{% for object in object_list %}
<tr>
<!--    <td><a href="{{object.get_absolute_url}}">{{object.name}}</a></td> -->
    <td>{{object.name}}</td>
    <td>{{ object.starttime }}</td>
    <td>{{ object.endtime }}</td>
    <td><a href="{{object.location.get_absolute_url}}">{{ object.location.name }}</a></td>
</tr>
{% endfor %}
</table>
<!--        <a class="btn btn-primary" href="{% url 'focus:focus_training_create' %}">Neues Training</a> -->

  <h4>&nbsp;Wenn Du weitere Details erfahren möchtest, dann melde Dich heute noch an:</h4>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
    <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
  {% else %}
<!--<p><a class="btn btn-default" href="{% url 'focus:focus_training_list' %}">Trainings</a></p> -->
<tr>
    <td>Was</td>
    <td>Von</td>
    <td>Bis</td>
    <td>Wo</td>
    <td>Anmeldung bis</td>
    <td>Wie melde ich mich an?</td>
    <td>Dabei?</td>
</tr>
{% for object in object_list %}
<tr>
<!--    <td><a href="{{object.get_absolute_url}}">{{object.name}}</a></td> -->
    <td><a href="{{object.get_absolute_url}}">{{object.name}}</a></td>
    <td>{{ object.starttime }}</td>
    <td>{{ object.endtime }}</td>
    <td><a href="{{object.location.get_absolute_url}}">{{ object.location.name }}</a></td>
    <td>{{ object.sign_in_date }}</td>
    <td>{{ object.subscription }}</td>
        {% csrf_token %}
    {% if object|competitor:user %}
        <td><div class="form-group" enctype="multipart/form-data">
                <button type="submit" value={{ object.pk }} name="abmelden" class="btn btn-primary btn-error">
                    Abmelden:(  </button>
        </div></td>
    {% else %}
        <td><div class="form-group" enctype="multipart/form-data">
                <button type="submit" value={{ object.pk }} name="anmelden" class="btn btn-primary btn-success">
                    {% if object.selfsubscription %}   Ich habe mich angemeldet wie links beschrieben! {% else %} Ich möchte mich anmelden {% endif %}  </button>
        </div></td>
    {% endif %}
</tr>
{% endfor %}
</table>
<!--        <a class="btn btn-primary" href="{% url 'focus:focus_training_create' %}">Neues Training</a> -->
</div>
    {% endif %}
</form>
{% endblock %}

src/focus/templates/focus/competition_list_old.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load customtags %}

{% block title %}{{ block.super }}Trainings{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="competition" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1 style="color:#ffffff">{% include "_brandname.html" %}</h1>
        <h4 style="color:#ffffff">Engagement, Kameradschaft, Bodenständigkeit.</h4>
      </div>
    </div>
  </div>
</div>

  {% if not user.is_authenticated %}
<div class="container-fluid">
<h1>Wettkämpfe & Events</h1>

<div class="container-fluid">
<iframe src="https://calendar.google.com/calendar/embed?src=g7trtnc4b6ecbg490ph5f7gf88%40group.calendar.google.com&ctz=Europe%2FZurich" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe><tr>
    <td>Was</td>
    <td>Von</td>
    <td>Bis</td>
    <td>Wo</td>
</tr>
{% for object in object_list %}
<tr>
<!--    <td><a href="{{object.get_absolute_url}}">{{object.name}}</a></td> -->
    <td>{{object.name}}</td>
    <td>{{ object.starttime }}</td>
    <td>{{ object.endtime }}</td>
    <td><a href="{{object.location.get_absolute_url}}">{{ object.location.name }}</a></td>
</tr>
{% endfor %}
</table>
<!--        <a class="btn btn-primary" href="{% url 'focus:focus_training_create' %}">Neues Training</a> -->
</div>

  <h4>&nbsp;Wenn Du weitere Details erfahren möchtest, dann melde Dich heute noch an:</h4>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
    <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
  {% else %}
<!--<p><a class="btn btn-default" href="{% url 'focus:focus_training_list' %}">Trainings</a></p> -->
<form id="abmelden" method="post">
<div class="container-fluid">
    <h1 >Wettkämpfe & Events</h1>
<table class="table table-hover table-bordered table-striped table-condensed">
<tr>
    <td>Was</td>
    <td>Von</td>
    <td>Bis</td>
    <td>Wo</td>
    <td>Beschreib</td>
    <td>Link</td>
    <td>Anmeldung bis</td>
    <td>Treffpunkt</td>
    <td>Treffzeit</td>
    <td>Dabei?</td>
</tr>
{% for object in object_list %}
<tr>
<!--    <td><a href="{{object.get_absolute_url}}">{{object.name}}</a></td> -->
    <td>{{object.name}}</td>
    <td>{{ object.starttime }}</td>
    <td>{{ object.endtime }}</td>
    <td><a href="{{object.location.get_absolute_url}}">{{ object.location.name }}</a></td>
    <td>{{ object.short_description }}</td>
    <td>{{ object.link }}</td>
    <td>{{ object.sign_in_date }}</td>
    <td><a href="{{object.meetingpoint.get_absolute_url}}">{{ object.meetingpoint.name }}</a></td>
    <td>{{ object.meeting_time }}</td>
        {% csrf_token %}
    {% if object|competitor:user %}
        <td><div class="form-group" enctype="multipart/form-data">
                <button type="submit" value={{ object.pk }} name="abmelden" class="btn btn-primary btn-error">
                    Abmelden  </button>
        </div></td>
    {% else %}
        <td><div class="form-group" enctype="multipart/form-data">
                <button type="submit" value={{ object.pk }} name="anmelden" class="btn btn-primary btn-success">
                    Anmelden  </button>
        </div></td>
    {% endif %}
</tr>
{% endfor %}
</table>
<!--        <a class="btn btn-primary" href="{% url 'focus:focus_training_create' %}">Neues Training</a> -->
</div>
</form>
    {% endif %}
{% endblock %}

src/focus/templates/focus/competitor_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'focus_competitor_list' %}">Competitor Listing</a></p>
<table class="table">
<tr><td>slug</td><td>{{ object.slug }}</td></tr>
<tr><td>created</td><td>{{ object.created }}</td></tr>
<tr><td>last_updated</td><td>{{ object.last_updated }}</td></tr>
<tr><td>yesorno</td><td>{{ object.yesorno }}</td></tr>
<tr><td>note</td><td>{{ object.note }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit Competitor</a>

{% endblock %}

src/focus/templates/focus/event_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'focus_event_list' %}">Event Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

src/focus/templates/focus/training_list.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load customtags %}

{% block title %}{{ block.super }}Trainings{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="training" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}
{% csrf_token %}
<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1 style="color:#ffffff">{% include "_brandname.html" %}</h1>
        <h4 style="color:#ffffff">Engagement, Kameradschaft, Bodenständigkeit.</h4>
      </div>
    </div>
  </div>
</div>
<!--<p><a class="btn btn-default" href="{% url 'focus:focus_training_list' %}">Trainings</a></p> -->

  {% if not user.is_authenticated %}
<div class="container-fluid">
<h1>&nbsp;Trainings</h1>

<table class="table table-hover table-bordered table-striped table-condensed">
<tr>
    <td>Name</td>
    <td>Datum</td>
    <td>Von</td>
    <td>Bis</td>
    <td>Wo</td>
</tr>
{% for object in object_list %}
<tr>
<!--    <td><a href="{{object.get_absolute_url}}">{{object.name}}</a></td> -->
    <td>{{object.name}}</td>
    <td>{{ object.starttime.weekday|strday }}, {{ object.starttime.date }}</td>
    <td>{{ object.starttime.time }}</td>
    <td>{{ object.endtime.time }}</td>
    <td><a href="{{object.location.get_absolute_url}}">{{ object.location.name }}</a></td>
</tr>
{% endfor %}
</table>
<!--        <a class="btn btn-primary" href="{% url 'focus:focus_training_create' %}">Neues Training</a> -->
</div>

  <h4>&nbsp;Wenn Du weitere Details erfahren möchtest, dann melde Dich heute noch an:</h4>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
    <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>

{% else %}

{% if user.profile.is_coach %}
<p><a class="btn btn-default" href="{% url 'focus:focus_training_create' %}">Neues Training</a></p>
{% endif %}

<form id="trainings" method="post">
<div class="container-fluid">
    <h1 >Trainings</h1>
<table class="table table-hover table-bordered table-striped table-condensed">
<tr>
    <td>Name</td>
    <td>Datum</td>
    <td>Von</td>
    <td>Bis</td>
    <td>Wo</td>
    <td>Beschreib</td>
    <td>Intensität</td>
    <td>Dabei?</td>
</tr>
{% for object in object_list %}
<tr>
<!--    <td><a href="{{object.get_absolute_url}}">{{object.name}}</a></td> -->
    <td>{% if user.profile.is_coach %}<a href="{{object.get_absolute_url}}">{% endif %}{{object.name}}</a></td>
    <td>{{ object.starttime.weekday|strday }}, {{ object.starttime.date }}</td>
    <td>{{ object.starttime.time }}</td>
    <td>{{ object.endtime.time }}</td>
    <td><a href="{{object.location.get_absolute_url}}">{{ object.location.name }}</a></td>
    <td>{{ object.short_description }}</td>
    <td>{{ object.intensity }}</td>
            {% csrf_token %}
    {% if object|trainingpresence:user %}
        <td><div class="form-group" enctype="multipart/form-data">
                <button type="submit" value={{ object.pk }} name="anmelden" class="btn btn-primary btn-success">
                    Anmelden  </button>
        </div></td>
    {% else %}
        <td><div class="form-group" enctype="multipart/form-data">
                <button type="submit" value={{ object.pk }} name="abmelden" class="btn btn-primary btn-error">
                    Abmelden  </button>
        </div></td>
    {% endif %}
</tr>
{% endfor %}
</table>

<!--        <a class="btn btn-primary" href="{% url 'focus:focus_training_create' %}">Neues Training</a> -->
</div>
</form>
{% endif %}
{% endblock %}